resources:
- cluster-api-cleaner-vsphere.yaml
- cluster-api-ipam-provider-in-cluster.yaml
- cluster-api-provider-vsphere.yaml
- dex-app.yaml
- dex-operator.yaml
- dns-operator-route53.yaml
- etcd-backup-operator.yaml
- event-exporter-app.yaml
- exception-recommender.yaml
- falco.yaml
- konfiguration.v2.yaml
- teleport-operator.yaml
- teleport-tbot.yaml
- tempo.yaml
- trivy-operator.yaml
- trivy.yaml
