apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "true"
  creationTimestamp: null
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    config-controller.giantswarm.io/version: 0.0.0
  name: app-exporter-unique
  namespace: giantswarm
spec:
  catalog: control-plane-catalog
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: app-exporter
  namespace: giantswarm
  userConfig:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  version: 0.4.0
status:
  appVersion: ""
  release:
    lastDeployed: null
    status: ""
  version: ""